/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package archivo;

import java.awt.Toolkit;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author tutaa
 */
public class Calendario extends javax.swing.JFrame {

    String texto = null;
    String materiac = null;
    String horita = null;
    String fechayhora = "SELECCIONE EL DÍA";

    /**
     * Creates new form Calendario
     */
    public Calendario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("CALENDARIO");
        this.setResizable(false);
        txt1.setEditable(false);
        fechayhora = "SELECCIONE EL DÍA";
        habilitarBotonSolicitar();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/icon.png")));

        jCalendar1.setMinSelectableDate(new Date());

    }

    public void habilitarBotonSolicitar() {
        if (txt1.getText().equals("")) {
            botonsolicitar.setEnabled(true);

        } else {
            botonsolicitar.setEnabled(false);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        canvas1 = new java.awt.Canvas();
        botonCuenta1 = new javax.swing.JButton();
        botonSesiones1 = new javax.swing.JButton();
        botonCambiarCuenta1 = new javax.swing.JButton();
        botonAtras1 = new javax.swing.JButton();
        botonCalendario1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        botonsolicitar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        materiascombo1 = new javax.swing.JComboBox<>();
        horacombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnlistausers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 251, 252));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(canvas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 496, -1, -1));

        botonCuenta1.setBackground(new java.awt.Color(185, 215, 234));
        botonCuenta1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonCuenta1.setForeground(new java.awt.Color(66, 120, 181));
        botonCuenta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo/notebook.png"))); // NOI18N
        botonCuenta1.setText("CUENTA");
        botonCuenta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCuenta1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonCuenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 184, 97));

        botonSesiones1.setBackground(new java.awt.Color(185, 215, 234));
        botonSesiones1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonSesiones1.setForeground(new java.awt.Color(66, 120, 181));
        botonSesiones1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo/message.png"))); // NOI18N
        botonSesiones1.setText("SESIONES");
        botonSesiones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSesiones1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonSesiones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 221, 184, 97));

        botonCambiarCuenta1.setBackground(new java.awt.Color(185, 215, 234));
        botonCambiarCuenta1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonCambiarCuenta1.setForeground(new java.awt.Color(66, 120, 181));
        botonCambiarCuenta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo/arrows.png"))); // NOI18N
        botonCambiarCuenta1.setText("CAMBIAR CUENTA");
        botonCambiarCuenta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarCuenta1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonCambiarCuenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 324, 184, 97));

        botonAtras1.setBackground(new java.awt.Color(185, 215, 234));
        botonAtras1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonAtras1.setForeground(new java.awt.Color(66, 120, 181));
        botonAtras1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo/close.png"))); // NOI18N
        botonAtras1.setText("CERRAR");
        botonAtras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtras1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonAtras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 427, 184, 97));

        botonCalendario1.setBackground(new java.awt.Color(185, 215, 234));
        botonCalendario1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonCalendario1.setForeground(new java.awt.Color(66, 120, 181));
        botonCalendario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo/calendar.png"))); // NOI18N
        botonCalendario1.setText("CALENDARIO");
        botonCalendario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalendario1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonCalendario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 118, 184, 97));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(118, 159, 205));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo/WhatsApp Image 2022-11-11 at 3.46.35 PM.jpeg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        jCalendar1.setBackground(new java.awt.Color(185, 215, 234));
        jCalendar1.setForeground(new java.awt.Color(66, 120, 181));
        jCalendar1.setDecorationBackgroundColor(new java.awt.Color(247, 251, 252));
        jCalendar1.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jCalendar1HierarchyChanged(evt);
            }
        });
        jCalendar1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jCalendar1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 390, 230));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(118, 159, 205));
        jLabel1.setText("HORA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, -1, -1));

        botonsolicitar.setBackground(new java.awt.Color(185, 215, 234));
        botonsolicitar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonsolicitar.setForeground(new java.awt.Color(118, 159, 205));
        botonsolicitar.setText("Solicitar");
        botonsolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsolicitarActionPerformed(evt);
            }
        });
        jPanel1.add(botonsolicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 90, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(118, 159, 205));
        jLabel2.setText("FECHA NUEVA SESION");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(118, 159, 205));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo/image.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 100, -1));

        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt1KeyReleased(evt);
            }
        });
        jPanel1.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 190, 30));

        materiascombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arquitectura de Hardware", "Cálculo Diferencial", "Desarrollo de App", "Física Mecánica", "Inglés Básico", "Programación Orientada a Objetos" }));
        materiascombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiascombo1ActionPerformed(evt);
            }
        });
        jPanel1.add(materiascombo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 190, 30));

        horacombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8:00 a.m", "9:00 a.m", "10:00 a.m", "11:00 a.m", "12:00 mm", "1:00 p.m", "2:00 p.m", "3:00 p.m", "4:00 p.m", "5:00 p.m", "6:00 p.m", "7:00 p.m", "8:00 p.m" }));
        horacombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                horacomboItemStateChanged(evt);
            }
        });
        horacombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horacomboActionPerformed(evt);
            }
        });
        jPanel1.add(horacombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 130, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(118, 159, 205));
        jLabel3.setText("MATERIA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, -1, -1));

        btnlistausers.setBackground(new java.awt.Color(185, 215, 234));
        btnlistausers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnlistausers.setForeground(new java.awt.Color(118, 159, 205));
        btnlistausers.setText("Ver lista de estudiantes");
        btnlistausers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistausersActionPerformed(evt);
            }
        });
        jPanel1.add(btnlistausers, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
        habilitarBotonSolicitar();
        this.texto = txt1.getText();

    }//GEN-LAST:event_txt1ActionPerformed

    private void materiascombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiascombo1ActionPerformed
        // TODO add your handling code here:
        this.materiac = materiascombo1.getSelectedItem().toString();
    }//GEN-LAST:event_materiascombo1ActionPerformed

    private void jCalendar1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jCalendar1AncestorAdded

    }//GEN-LAST:event_jCalendar1AncestorAdded

    private void jCalendar1HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jCalendar1HierarchyChanged
        txt1.setText("");
        habilitarBotonSolicitar();
        fechayhora = null;
        jCalendar1.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                SimpleDateFormat ff = new SimpleDateFormat("dd/MM/yyyy");
                String fechita = (ff.format(jCalendar1.getCalendar().getTime()));
                String horita = horacombo.getSelectedItem().toString();
                String fechayhora = fechita + " - " + horita;
                txt1.setText(fechayhora);
            }

        });


    }//GEN-LAST:event_jCalendar1HierarchyChanged

    private void horacomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horacomboActionPerformed

    }//GEN-LAST:event_horacomboActionPerformed

    private void horacomboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_horacomboItemStateChanged
        // TODO add your handling code here:

        txt1.setText("SELECCIONE EL DÍA");
    }//GEN-LAST:event_horacomboItemStateChanged

    private void txt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyReleased
        // TODO add your handling code here:
        habilitarBotonSolicitar();


    }//GEN-LAST:event_txt1KeyReleased

    private void btnlistausersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistausersActionPerformed
        // TODO add your handling code here:
        ListaEstudiantes lista = new ListaEstudiantes();
        lista.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnlistausersActionPerformed

    private void botonCuenta1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botonCuenta1ActionPerformed
        Cuenta cuenta = new Cuenta();
        cuenta.setVisible(true);
        this.setVisible(false);
    }// GEN-LAST:event_botonCuenta1ActionPerformed

    private void botonSesiones1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botonSesiones1ActionPerformed
        Sesiones ses = new Sesiones();
        ses.setVisible(true);
        this.setVisible(false);
    }// GEN-LAST:event_botonSesiones1ActionPerformed

    private void botonCambiarCuenta1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botonCambiarCuenta1ActionPerformed
        PantallaInicio pantalla = new PantallaInicio();
        pantalla.setVisible(true);
        this.setVisible(false);
    }// GEN-LAST:event_botonCambiarCuenta1ActionPerformed

    private void botonAtras1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botonAtras1ActionPerformed
        System.exit(0);
    }// GEN-LAST:event_botonAtras1ActionPerformed

    private void botonCalendario1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botonCalendario1ActionPerformed
        JOptionPane.showMessageDialog(null, "YA SE ENCUENTRA EN ESTA PESTAÑA");
    }// GEN-LAST:event_botonCalendario1ActionPerformed

    private void botonsolicitarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botonsolicitarActionPerformed
        Archivo archivo = new Archivo();
        archivo.crearArchivo();
        String materia = materiascombo1.getSelectedItem().toString();
        String link = "";
        if (materiascombo1.getSelectedItem().toString().equals("Arquitectura de Hardware")) {
            link = "https://acortar.link/c1tNge";

        }
        if (materiascombo1.getSelectedItem().toString().equals("Desarrollo de App")) {
            link = "https://meet.google.com/bzb-ufqs-cgx";

        }
        if (materiascombo1.getSelectedItem().toString().equals("Cálculo Diferencial")) {
            link = "https://meet.google.com/xnt-wqwx-scw";

        }
        if (materiascombo1.getSelectedItem().toString().equals("Física Mecánica")) {
            link = "https://meet.google.com/vim-mpxm-kck";

        }
        if (materiascombo1.getSelectedItem().toString().equals("Programación Orientada a Objetos")) {
            link = "https://acortar.link/gL8WsB";

        }
        if (materiascombo1.getSelectedItem().toString().equals("Inglés Básico")) {
            link = "https://acortar.link/xudRLP";

        }
        String fecha = txt1.getText();
        fecha = fecha.replace("01", "");
        Random rd = new Random();

        Persona persona = new Persona(materia, link, fecha);
        archivo.escribirEnArchivo(persona);
        JOptionPane.showMessageDialog(null, "SE HIZO LA SOLICITUD");

    }// GEN-LAST:event_botonsolicitarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calendario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras1;
    private javax.swing.JButton botonCalendario1;
    private javax.swing.JButton botonCambiarCuenta1;
    private javax.swing.JButton botonCuenta1;
    private javax.swing.JButton botonSesiones1;
    private javax.swing.JButton botonsolicitar;
    private javax.swing.JButton btnlistausers;
    private java.awt.Canvas canvas1;
    private javax.swing.JComboBox<String> horacombo;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> materiascombo1;
    private javax.swing.JTextField txt1;
    // End of variables declaration//GEN-END:variables
}
