/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package archivo;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author tutaa
 */
public class Cuenta extends javax.swing.JFrame {

    /**
     * Creates new form Cuenta
     */
    public static String biografia = "";

    public Cuenta() {
        initComponents();

        this.setLocationRelativeTo(null);
        this.setTitle("CUENTA");
        this.setResizable(false);
        Registrar rg = new Registrar();
        PantallaInicio pi = new PantallaInicio();
        String correito = pi.correolog;
        correo.setText(correito);
        Conexion cn = new Conexion();
        biografiamostrar.setText(biografia);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/icon.png")));

        Connection con = null;
        try {
            con = cn.getConection();
            cn.ps = con.prepareCall("SELECT nombre FROM usuarios WHERE correo = ?");
            cn.ps.setString(1, correito);

            cn.rs = cn.ps.executeQuery();
            if (cn.rs.next()) {
                nombretxt.setText(cn.rs.getString("nombre"));

            } else {
                System.out.println("No hay resultados");
            }

        } catch (Exception e) {
            System.err.println(e);

        }
        habilitarBotonGuardar();
        habilitarBotonCancelar();

    }

    public void habilitarBotonGuardar() {
        if (biografiaescribir.getText().length() < 10) {
            botonGuardar.setEnabled(false);

        } else {
            botonGuardar.setEnabled(true);

        }
    }

    public void habilitarBotonCancelar() {
        if (biografiaescribir.getText().length() < 1) {
            botonCancelar.setEnabled(false);

        } else {
            botonCancelar.setEnabled(true);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        canvas1 = new java.awt.Canvas();
        botonCuenta = new javax.swing.JButton();
        botonSesiones = new javax.swing.JButton();
        botonCambiarCuenta = new javax.swing.JButton();
        botonAtras = new javax.swing.JButton();
        botonCalendario = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        biografiaescribir = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        correo = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nombretxt = new javax.swing.JLabel();
        biografiamostrar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(247, 251, 252));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(118, 159, 205));
        jLabel1.setText("Biografía:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));
        jPanel1.add(canvas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 496, -1, -1));

        botonCuenta.setBackground(new java.awt.Color(185, 215, 234));
        botonCuenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonCuenta.setForeground(new java.awt.Color(66, 120, 181));
        botonCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo/notebook.png"))); // NOI18N
        botonCuenta.setText("CUENTA");
        botonCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(botonCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 184, 97));

        botonSesiones.setBackground(new java.awt.Color(185, 215, 234));
        botonSesiones.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonSesiones.setForeground(new java.awt.Color(66, 120, 181));
        botonSesiones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo/message.png"))); // NOI18N
        botonSesiones.setText("SESIONES");
        botonSesiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSesionesActionPerformed(evt);
            }
        });
        jPanel1.add(botonSesiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 221, 184, 97));

        botonCambiarCuenta.setBackground(new java.awt.Color(185, 215, 234));
        botonCambiarCuenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonCambiarCuenta.setForeground(new java.awt.Color(66, 120, 181));
        botonCambiarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo/arrows.png"))); // NOI18N
        botonCambiarCuenta.setText("CAMBIAR CUENTA");
        botonCambiarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(botonCambiarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 324, 184, 97));

        botonAtras.setBackground(new java.awt.Color(185, 215, 234));
        botonAtras.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonAtras.setForeground(new java.awt.Color(66, 120, 181));
        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo/close.png"))); // NOI18N
        botonAtras.setText("CERRAR");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(botonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 427, 184, 97));

        botonCalendario.setBackground(new java.awt.Color(185, 215, 234));
        botonCalendario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonCalendario.setForeground(new java.awt.Color(66, 120, 181));
        botonCalendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo/calendar.png"))); // NOI18N
        botonCalendario.setText("CALENDARIO");
        botonCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalendarioActionPerformed(evt);
            }
        });
        jPanel1.add(botonCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 118, 184, 97));

        biografiaescribir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                biografiaescribirKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(biografiaescribir);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 392, 311, 60));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(118, 159, 205));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo/WhatsApp Image 2022-11-11 at 3.43.50 PM.jpeg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(118, 159, 205));
        jLabel3.setText("Correo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));

        correo.setFont(new java.awt.Font("Arial Narrow", 2, 18)); // NOI18N
        correo.setForeground(new java.awt.Color(118, 159, 205));
        correo.setText(" ");
        jPanel1.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 290, -1));

        botonGuardar.setBackground(new java.awt.Color(185, 215, 234));
        botonGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonGuardar.setForeground(new java.awt.Color(66, 120, 181));
        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 464, 113, 37));

        botonCancelar.setBackground(new java.awt.Color(185, 215, 234));
        botonCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(66, 120, 181));
        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(637, 464, 113, 37));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(118, 159, 205));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo/image.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 100, -1));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(118, 159, 205));
        jLabel7.setText("Nombre:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        nombretxt.setFont(new java.awt.Font("Arial Narrow", 2, 18)); // NOI18N
        nombretxt.setForeground(new java.awt.Color(118, 159, 205));
        nombretxt.setText(" ");
        jPanel1.add(nombretxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 290, -1));

        biografiamostrar.setFont(new java.awt.Font("Arial Narrow", 2, 18)); // NOI18N
        biografiamostrar.setForeground(new java.awt.Color(118, 159, 205));
        biografiamostrar.setText(" ");
        jPanel1.add(biografiamostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 360, -1));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(118, 159, 205));
        jLabel4.setText("Biografía:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 550));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(118, 159, 205));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo/image.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void biografiaescribirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_biografiaescribirKeyReleased
        // TODO add your handling code here:
        habilitarBotonGuardar();
        habilitarBotonCancelar();
    }//GEN-LAST:event_biografiaescribirKeyReleased

    private void botonCalendarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botonCalendarioActionPerformed
        Calendario cal = new Calendario();
        cal.setVisible(true);
        this.setVisible(false);
    }// GEN-LAST:event_botonCalendarioActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botonAtrasActionPerformed
        System.exit(0);
    }// GEN-LAST:event_botonAtrasActionPerformed

    private void botonCambiarCuentaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botonCambiarCuentaActionPerformed
        PantallaInicio pantalla = new PantallaInicio();
        pantalla.setVisible(true);
        this.setVisible(false);
    }// GEN-LAST:event_botonCambiarCuentaActionPerformed

    private void botonSesionesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botonSesionesActionPerformed
        Sesiones ses = new Sesiones();
        ses.setVisible(true);
        this.setVisible(false);
    }// GEN-LAST:event_botonSesionesActionPerformed

    private void botonCuentaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botonCuentaActionPerformed
        JOptionPane.showMessageDialog(null, "YA SE ENCUENTRA EN ESTA PESTAÑA");
    }// GEN-LAST:event_botonCuentaActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botonGuardarActionPerformed
        biografia = biografiaescribir.getText();
        biografiamostrar.setText(biografia);
        JOptionPane.showMessageDialog(null, "GUARDADO CORRECTAMENTE");
    }// GEN-LAST:event_botonGuardarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botonCancelarActionPerformed
        biografiaescribir.setText("");

    }// GEN-LAST:event_botonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cuenta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cuenta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cuenta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cuenta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane biografiaescribir;
    private javax.swing.JLabel biografiamostrar;
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonCalendario;
    private javax.swing.JButton botonCambiarCuenta;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonCuenta;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonSesiones;
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel correo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nombretxt;
    // End of variables declaration//GEN-END:variables
}
