/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package archivo;

import java.awt.Component;
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author tutaa
 */
public class TrikiVisual extends javax.swing.JFrame {

    String turno = "X";
    String siguienteJuego = "O";
    String nombrej1 = "";
    String nombrej2 = "";
    String turnonom = "";
    JLabel lbs[] = new JLabel[9];

    int vs[][] = {
        {1, 2, 3},
        {4, 5, 6},
        {7, 8, 9},
        {2, 5, 8},
        {3, 6, 9},
        {1, 5, 9},
        {3, 5, 7},};

    /**
     * Creates new form TrikiVisual
     */
    public TrikiVisual() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("TRIKI");
        this.setResizable(false);
        habilitarBotonIniciar();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/icon.png")));
        lbs[0] = espacio1;
        lbs[1] = espacio2;
        lbs[2] = espacio3;
        lbs[3] = espacio4;
        lbs[4] = espacio5;
        lbs[5] = espacio6;
        lbs[6] = espacio7;
        lbs[7] = espacio8;
        lbs[8] = espacio9;

        for (Component a : jPanel3.getComponents()) {
            a.setEnabled(false);

        }

    }

    public void habilitarBotonIniciar() {
        if ((nombre1.getText().length() > 2) && (nombre2.getText().length() > 2)) {
            botoniniciar.setEnabled(true);

        } else {
            botoniniciar.setEnabled(false);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        canvas1 = new java.awt.Canvas();
        botonCuenta1 = new javax.swing.JButton();
        botonSesiones1 = new javax.swing.JButton();
        botonCambiarCuenta1 = new javax.swing.JButton();
        botonAtras1 = new javax.swing.JButton();
        botonCalendario1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        botonreiniciar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        espacio11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        espacio1 = new javax.swing.JLabel();
        espacio2 = new javax.swing.JLabel();
        espacio3 = new javax.swing.JLabel();
        espacio4 = new javax.swing.JLabel();
        espacio5 = new javax.swing.JLabel();
        espacio6 = new javax.swing.JLabel();
        espacio7 = new javax.swing.JLabel();
        espacio8 = new javax.swing.JLabel();
        espacio9 = new javax.swing.JLabel();
        espacio10 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JTextField();
        nombre2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        turnotext = new javax.swing.JLabel();
        botoniniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 251, 252));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(canvas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 496, -1, -1));

        botonCuenta1.setBackground(new java.awt.Color(185, 215, 234));
        botonCuenta1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonCuenta1.setForeground(new java.awt.Color(66, 120, 181));
        botonCuenta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo/notebook.png"))); // NOI18N
        botonCuenta1.setText("CUENTA");
        botonCuenta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCuenta1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonCuenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 184, 97));

        botonSesiones1.setBackground(new java.awt.Color(185, 215, 234));
        botonSesiones1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonSesiones1.setForeground(new java.awt.Color(66, 120, 181));
        botonSesiones1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo/message.png"))); // NOI18N
        botonSesiones1.setText("SESIONES");
        botonSesiones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSesiones1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonSesiones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 221, 184, 97));

        botonCambiarCuenta1.setBackground(new java.awt.Color(185, 215, 234));
        botonCambiarCuenta1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonCambiarCuenta1.setForeground(new java.awt.Color(66, 120, 181));
        botonCambiarCuenta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo/arrows.png"))); // NOI18N
        botonCambiarCuenta1.setText("CAMBIAR CUENTA");
        botonCambiarCuenta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarCuenta1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonCambiarCuenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 324, 184, 97));

        botonAtras1.setBackground(new java.awt.Color(185, 215, 234));
        botonAtras1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonAtras1.setForeground(new java.awt.Color(66, 120, 181));
        botonAtras1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo/close.png"))); // NOI18N
        botonAtras1.setText("CERRAR");
        botonAtras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtras1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonAtras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 427, 184, 97));

        botonCalendario1.setBackground(new java.awt.Color(185, 215, 234));
        botonCalendario1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonCalendario1.setForeground(new java.awt.Color(66, 120, 181));
        botonCalendario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo/calendar.png"))); // NOI18N
        botonCalendario1.setText("CALENDARIO");
        botonCalendario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalendario1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonCalendario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 118, 184, 97));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(118, 159, 205));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo/image.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 100, -1));

        botonreiniciar.setBackground(new java.awt.Color(185, 215, 234));
        botonreiniciar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonreiniciar.setForeground(new java.awt.Color(118, 159, 205));
        botonreiniciar.setText("Reiniciar");
        botonreiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonreiniciarActionPerformed(evt);
            }
        });
        jPanel1.add(botonreiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 90, 30));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(118, 159, 205));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo/triki.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(247, 251, 252));

        espacio11.setBackground(new java.awt.Color(185, 215, 234));
        espacio11.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        espacio11.setForeground(new java.awt.Color(255, 255, 255));
        espacio11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        espacio11.setText("O");
        espacio11.setOpaque(true);
        espacio11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                espacio11MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                espacio11MousePressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(247, 251, 252));

        espacio1.setBackground(new java.awt.Color(185, 215, 234));
        espacio1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        espacio1.setForeground(new java.awt.Color(255, 255, 255));
        espacio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        espacio1.setOpaque(true);
        espacio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                espacio1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                espacio1MousePressed(evt);
            }
        });

        espacio2.setBackground(new java.awt.Color(185, 215, 234));
        espacio2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        espacio2.setForeground(new java.awt.Color(255, 255, 255));
        espacio2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        espacio2.setOpaque(true);
        espacio2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                espacio2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                espacio2MousePressed(evt);
            }
        });

        espacio3.setBackground(new java.awt.Color(185, 215, 234));
        espacio3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        espacio3.setForeground(new java.awt.Color(255, 255, 255));
        espacio3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        espacio3.setOpaque(true);
        espacio3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                espacio3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                espacio3MousePressed(evt);
            }
        });

        espacio4.setBackground(new java.awt.Color(185, 215, 234));
        espacio4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        espacio4.setForeground(new java.awt.Color(255, 255, 255));
        espacio4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        espacio4.setOpaque(true);
        espacio4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                espacio4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                espacio4MousePressed(evt);
            }
        });

        espacio5.setBackground(new java.awt.Color(185, 215, 234));
        espacio5.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        espacio5.setForeground(new java.awt.Color(255, 255, 255));
        espacio5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        espacio5.setOpaque(true);
        espacio5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                espacio5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                espacio5MousePressed(evt);
            }
        });

        espacio6.setBackground(new java.awt.Color(185, 215, 234));
        espacio6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        espacio6.setForeground(new java.awt.Color(255, 255, 255));
        espacio6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        espacio6.setOpaque(true);
        espacio6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                espacio6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                espacio6MousePressed(evt);
            }
        });

        espacio7.setBackground(new java.awt.Color(185, 215, 234));
        espacio7.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        espacio7.setForeground(new java.awt.Color(255, 255, 255));
        espacio7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        espacio7.setOpaque(true);
        espacio7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                espacio7MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                espacio7MousePressed(evt);
            }
        });

        espacio8.setBackground(new java.awt.Color(185, 215, 234));
        espacio8.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        espacio8.setForeground(new java.awt.Color(255, 255, 255));
        espacio8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        espacio8.setOpaque(true);
        espacio8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                espacio8MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                espacio8MousePressed(evt);
            }
        });

        espacio9.setBackground(new java.awt.Color(185, 215, 234));
        espacio9.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        espacio9.setForeground(new java.awt.Color(255, 255, 255));
        espacio9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        espacio9.setOpaque(true);
        espacio9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                espacio9MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                espacio9MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(espacio7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(espacio8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(espacio9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(espacio1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(espacio2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(espacio3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(espacio4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(espacio5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(espacio6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(espacio1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(espacio2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(espacio3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(espacio4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(espacio5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(espacio6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(espacio7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(espacio8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(espacio9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        espacio10.setBackground(new java.awt.Color(185, 215, 234));
        espacio10.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        espacio10.setForeground(new java.awt.Color(255, 255, 255));
        espacio10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        espacio10.setText("X");
        espacio10.setOpaque(true);
        espacio10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                espacio10MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                espacio10MousePressed(evt);
            }
        });

        nombre1.setBackground(new java.awt.Color(255, 255, 255));
        nombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre1ActionPerformed(evt);
            }
        });
        nombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombre1KeyReleased(evt);
            }
        });

        nombre2.setBackground(new java.awt.Color(255, 255, 255));
        nombre2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombre2KeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(118, 159, 205));
        jLabel1.setText("NOMBRE:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(118, 159, 205));
        jLabel2.setText("NOMBRE:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(118, 159, 205));
        jLabel3.setText("TURNO:");

        turnotext.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        turnotext.setForeground(new java.awt.Color(118, 159, 205));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(espacio10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombre1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(espacio11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombre2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(turnotext)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(turnotext))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(espacio10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(espacio11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 590, 420));

        botoniniciar.setBackground(new java.awt.Color(185, 215, 234));
        botoniniciar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botoniniciar.setForeground(new java.awt.Color(118, 159, 205));
        botoniniciar.setText("Iniciar");
        botoniniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoniniciarActionPerformed(evt);
            }
        });
        jPanel1.add(botoniniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 936, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCuenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCuenta1ActionPerformed
        // TODO add your handling code here:
        Cuenta cuenta = new Cuenta();
        cuenta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonCuenta1ActionPerformed

    private void botonSesiones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSesiones1ActionPerformed
        // TODO add your handling code here:
        Sesiones ses = new Sesiones();
        ses.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonSesiones1ActionPerformed

    private void botonCambiarCuenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarCuenta1ActionPerformed
        // TODO add your handling code here:
        PantallaInicio pantalla = new PantallaInicio();
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonCambiarCuenta1ActionPerformed

    private void botonAtras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtras1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonAtras1ActionPerformed

    private void botonCalendario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalendario1ActionPerformed
        // TODO add your handling code here:
        Calendario cal = new Calendario();
        cal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonCalendario1ActionPerformed

    private void espacio2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espacio2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_espacio2MouseClicked

    private void espacio2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espacio2MousePressed
        // TODO add your handling code here:

        presionar(2);
    }//GEN-LAST:event_espacio2MousePressed

    private void espacio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espacio1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_espacio1MouseClicked

    private void espacio1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espacio1MousePressed
        // TODO add your handling code here:

        presionar(1);
    }//GEN-LAST:event_espacio1MousePressed

    private void espacio3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espacio3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_espacio3MouseClicked

    private void espacio3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espacio3MousePressed
        // TODO add your handling code here:

        presionar(3);
    }//GEN-LAST:event_espacio3MousePressed

    private void espacio4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espacio4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_espacio4MouseClicked

    private void espacio4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espacio4MousePressed
        // TODO add your handling code here:

        presionar(4);
    }//GEN-LAST:event_espacio4MousePressed

    private void espacio5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espacio5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_espacio5MouseClicked

    private void espacio5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espacio5MousePressed
        // TODO add your handling code here:

        presionar(5);
    }//GEN-LAST:event_espacio5MousePressed

    private void espacio6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espacio6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_espacio6MouseClicked

    private void espacio6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espacio6MousePressed
        // TODO add your handling code here:

        presionar(6);
    }//GEN-LAST:event_espacio6MousePressed

    private void espacio7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espacio7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_espacio7MouseClicked

    private void espacio7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espacio7MousePressed
        // TODO add your handling code here:

        presionar(7);
    }//GEN-LAST:event_espacio7MousePressed

    private void espacio8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espacio8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_espacio8MouseClicked

    private void espacio8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espacio8MousePressed
        // TODO add your handling code here:

        presionar(8);
    }//GEN-LAST:event_espacio8MousePressed

    private void espacio9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espacio9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_espacio9MouseClicked

    private void espacio9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espacio9MousePressed
        // TODO add your handling code here:

        presionar(9);
    }//GEN-LAST:event_espacio9MousePressed

    private void botonreiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonreiniciarActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < lbs.length; i++) {
            lbs[i].setText("");

        }
        turno = siguienteJuego;
        if (siguienteJuego.equals("O")) {
            siguienteJuego = "X";

        } else {
            siguienteJuego = "O";

        }

    }//GEN-LAST:event_botonreiniciarActionPerformed

    private void botoniniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoniniciarActionPerformed
        // TODO add your handling code here:
        nombrej1 = nombre1.getText();
        nombrej2 = nombre2.getText();
        turnotext.setText(nombrej1);
        for (Component a : jPanel3.getComponents()) {
            a.setEnabled(true);

        }


    }//GEN-LAST:event_botoniniciarActionPerformed

    private void espacio10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espacio10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_espacio10MouseClicked

    private void espacio10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espacio10MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_espacio10MousePressed

    private void espacio11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espacio11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_espacio11MouseClicked

    private void espacio11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espacio11MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_espacio11MousePressed

    private void nombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre1ActionPerformed

    private void nombre1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre1KeyReleased
        // TODO add your handling code here:
        habilitarBotonIniciar();
    }//GEN-LAST:event_nombre1KeyReleased

    private void nombre2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre2KeyReleased
        // TODO add your handling code here:
        habilitarBotonIniciar();
    }//GEN-LAST:event_nombre2KeyReleased

    public void presionar(int casilla) {
        if (lbs[casilla - 1].getText().equals("")) {
            lbs[casilla - 1].setText(turno);
        }
        cambiarTurno();
        comprobarGanador();

    }

    public void cambiarTurno() {
        if (turno.equals("X")) {
            turno = "O";
            turnonom = nombrej2;
            turnotext.setText(turnonom);

        } else {
            turno = "X";
            turnonom = nombrej1;
            turnotext.setText(turnonom);
        }

    }

    private void comprobarGanador() {
        for (int i = 0; i < vs.length; i++) {
            if (lbs[vs[i][0] - 1].getText().equals("X")
                    && lbs[vs[i][1] - 1].getText().equals("X")
                    && lbs[vs[i][2] - 1].getText().equals("X")) {

                JOptionPane.showMessageDialog(null, "GANÓ " + nombrej1);
            }

        }
        for (int i = 0; i < vs.length; i++) {
            if (lbs[vs[i][0] - 1].getText().equals("O")
                    && lbs[vs[i][1] - 1].getText().equals("O")
                    && lbs[vs[i][2] - 1].getText().equals("O")) {

                JOptionPane.showMessageDialog(null, "GANÓ " + nombrej2);
            }

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrikiVisual.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrikiVisual.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrikiVisual.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrikiVisual.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrikiVisual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras1;
    private javax.swing.JButton botonCalendario1;
    private javax.swing.JButton botonCambiarCuenta1;
    private javax.swing.JButton botonCuenta1;
    private javax.swing.JButton botonSesiones1;
    private javax.swing.JButton botoniniciar;
    private javax.swing.JButton botonreiniciar;
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel espacio1;
    private javax.swing.JLabel espacio10;
    private javax.swing.JLabel espacio11;
    private javax.swing.JLabel espacio2;
    private javax.swing.JLabel espacio3;
    private javax.swing.JLabel espacio4;
    private javax.swing.JLabel espacio5;
    private javax.swing.JLabel espacio6;
    private javax.swing.JLabel espacio7;
    private javax.swing.JLabel espacio8;
    private javax.swing.JLabel espacio9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nombre1;
    private javax.swing.JTextField nombre2;
    private javax.swing.JLabel turnotext;
    // End of variables declaration//GEN-END:variables

}
