/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISUAL.Pantallas;

import CODE.Clases.Archivo;
import CODE.Clases.Sesion;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.event.AncestorEvent;

/**
 *
 * @author tutaa
 */
public class PantallaCalendario extends javax.swing.JFrame {

    String texto, materia, hora, fechaConHora;

    /**
     * Creates new form Calendario
     */
    public PantallaCalendario() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/VISUAL/Imagenes/Logos/icon.png")));
        this.setLocationRelativeTo(null);
        this.setTitle("CALENDARIO");
        this.setResizable(false);
        tfFechaNuevaSesion.setEditable(false);
        tfFechaNuevaSesion.setText("SELECCIONE EL DIA.");
        btnSolicitar.setEnabled(desactivarBotonSolicitar());

        jCalendar.setMinSelectableDate(new Date());

    }

    public void cambiarTexto() {
        if (!tfFechaNuevaSesion.getText().isEmpty()) {
            fechaConHora = null;
            jCalendar.addPropertyChangeListener(new PropertyChangeListener() {
                @Override
                public void propertyChange(PropertyChangeEvent evt) {
                    cambiarHoraMateria();
                }
            });
        }
    }

    public boolean desactivarBotonSolicitar() {
        return (!tfFechaNuevaSesion.getText().equals("SELECCIONE EL DIA."));
    }

    public void cambiarHoraMateria() {

        SimpleDateFormat ff = new SimpleDateFormat("dd/MM/yyyy");
        String fecha = (ff.format(jCalendar.getCalendar().getTime()));

        String hora = cbHora.getSelectedItem().toString();
        materia = cbMateria.getSelectedItem().toString();
        String fechaConHora = fecha + " - " + hora + " - " + materia;
        tfFechaNuevaSesion.setText(fechaConHora);
        btnSolicitar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        canvas1 = new java.awt.Canvas();
        btnCuenta = new javax.swing.JButton();
        btnSesiones = new javax.swing.JButton();
        btnCambiarCuenta = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnCalendario = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jCalendar = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        btnSolicitar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfFechaNuevaSesion = new javax.swing.JTextField();
        cbMateria = new javax.swing.JComboBox<>();
        cbHora = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnVerListaEstudiantes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 251, 252));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(canvas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 496, -1, -1));

        btnCuenta.setBackground(new java.awt.Color(185, 215, 234));
        btnCuenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCuenta.setForeground(new java.awt.Color(66, 120, 181));
        btnCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo/notebook.png"))); // NOI18N
        btnCuenta.setText("CUENTA");
        btnCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 210, 97));

        btnSesiones.setBackground(new java.awt.Color(185, 215, 234));
        btnSesiones.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSesiones.setForeground(new java.awt.Color(66, 120, 181));
        btnSesiones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo/message.png"))); // NOI18N
        btnSesiones.setText("SESIONES");
        btnSesiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnSesiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 221, 210, 97));

        btnCambiarCuenta.setBackground(new java.awt.Color(185, 215, 234));
        btnCambiarCuenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCambiarCuenta.setForeground(new java.awt.Color(66, 120, 181));
        btnCambiarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo/arrows.png"))); // NOI18N
        btnCambiarCuenta.setText("CAMBIAR CUENTA");
        btnCambiarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCambiarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 324, 210, 97));

        btnCerrar.setBackground(new java.awt.Color(185, 215, 234));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(66, 120, 181));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo/close.png"))); // NOI18N
        btnCerrar.setText("CERRAR");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 427, 210, 97));

        btnCalendario.setBackground(new java.awt.Color(185, 215, 234));
        btnCalendario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCalendario.setForeground(new java.awt.Color(66, 120, 181));
        btnCalendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo/calendar.png"))); // NOI18N
        btnCalendario.setText("CALENDARIO");
        btnCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalendarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 118, 210, 97));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(118, 159, 205));
        jLabel4.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/VISUAL/Imagenes/Textos/imgSesionesProgramadas.jpeg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        jCalendar.setBackground(new java.awt.Color(185, 215, 234));
        jCalendar.setForeground(new java.awt.Color(66, 120, 181));
        jCalendar.setDecorationBackgroundColor(new java.awt.Color(247, 251, 252));
        jCalendar.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jCalendarHierarchyChanged(evt);
            }
        });
        jCalendar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jCalendarAncestorAdded(evt);
            }

            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }

            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(jCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 390, 230));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(118, 159, 205));
        jLabel1.setText("HORA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, -1, -1));

        btnSolicitar.setBackground(new java.awt.Color(185, 215, 234));
        btnSolicitar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSolicitar.setForeground(new java.awt.Color(118, 159, 205));
        btnSolicitar.setText("Solicitar");
        btnSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSolicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 90, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(118, 159, 205));
        jLabel2.setText("FECHA NUEVA SESIÓN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(118, 159, 205));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISUAL/Imagenes/Logos/imgUMBPequeño.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 100, -1));

        tfFechaNuevaSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFechaNuevaSesionActionPerformed(evt);
            }
        });
        tfFechaNuevaSesion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfFechaNuevaSesionKeyReleased(evt);
            }
        });
        jPanel1.add(tfFechaNuevaSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 290, 30));

        cbMateria.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Arquitectura de Hardware", "Cálculo Diferencial",
                        "Desarrollo de App", "Física Mecánica", "Inglés Básico", "Programación Orientada a Objetos" }));
        cbMateria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMateriaItemStateChanged(evt);
            }
        });
        cbMateria.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }

            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                cbMateriaAncestorMoved(evt);
            }

            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateriaActionPerformed(evt);
            }
        });
        cbMateria.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbMateriaPropertyChange(evt);
            }
        });
        jPanel1.add(cbMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 190, 30));

        cbHora.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "8:00 a.m", "9:00 a.m", "10:00 a.m", "11:00 a.m", "12:00 mm", "1:00 p.m", "2:00 p.m",
                        "3:00 p.m", "4:00 p.m", "5:00 p.m", "6:00 p.m", "7:00 p.m", "8:00 p.m" }));
        cbHora.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbHoraItemStateChanged(evt);
            }
        });
        cbHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHoraActionPerformed(evt);
            }
        });
        cbHora.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbHoraPropertyChange(evt);
            }
        });
        jPanel1.add(cbHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 130, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(118, 159, 205));
        jLabel3.setText("MATERIA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, -1, -1));

        btnVerListaEstudiantes.setBackground(new java.awt.Color(185, 215, 234));
        btnVerListaEstudiantes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerListaEstudiantes.setForeground(new java.awt.Color(118, 159, 205));
        btnVerListaEstudiantes.setText("Ver lista de estudiantes");
        btnVerListaEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerListaEstudiantesActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerListaEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // ! NO ELIMINAR ESTOS MÉTODOS VACÍOS
    protected void jCalendarAncestorAdded(AncestorEvent evt) {
    }

    protected void tfFechaNuevaSesionActionPerformed(ActionEvent evt) {
    }

    protected void cbMateriaAncestorMoved(AncestorEvent evt) {
    }

    private void cbMateriaItemStateChanged(java.awt.event.ItemEvent evt) {
    }

    private void cbHoraPropertyChange(java.beans.PropertyChangeEvent evt) {
    }

    private void cbMateriaPropertyChange(java.beans.PropertyChangeEvent evt) {
    }

    private void cbHoraItemStateChanged(java.awt.event.ItemEvent evt) {
    }

    private void tfFechaNuevaSesionKeyReleased(java.awt.event.KeyEvent evt) {
    }

    private void cbHoraActionPerformed(java.awt.event.ActionEvent evt) {
        cambiarHoraMateria();
        btnSolicitar.setEnabled(desactivarBotonSolicitar());
    }

    private void cbMateriaActionPerformed(java.awt.event.ActionEvent evt) {
        cambiarHoraMateria();
        btnSolicitar.setEnabled(desactivarBotonSolicitar());

    }

    private void jCalendarHierarchyChanged(java.awt.event.HierarchyEvent evt) {
        cambiarTexto();
        btnSolicitar.setEnabled(desactivarBotonSolicitar());
    }

    private void btnVerListaEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {
        PantallaListaEstudiantes lista = new PantallaListaEstudiantes();
        lista.setVisible(true);
        this.setVisible(false);
    }

    private void btnCuentaActionPerformed(java.awt.event.ActionEvent evt) {
        PantallaCuenta cuenta = new PantallaCuenta();
        cuenta.setVisible(true);
        this.setVisible(false);
    }

    private void btnSesionesActionPerformed(java.awt.event.ActionEvent evt) {
        PantallaSesiones ses = new PantallaSesiones();
        ses.setVisible(true);
        this.setVisible(false);
    }

    private void btnCambiarCuentaActionPerformed(java.awt.event.ActionEvent evt) {
        PantallaInicio pantalla = new PantallaInicio();
        pantalla.setVisible(true);
        this.setVisible(false);
    }

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    private void btnCalendarioActionPerformed(java.awt.event.ActionEvent evt) {
        JOptionPane.showMessageDialog(null, "YA SE ENCUENTRA EN ESTA PESTAÑA");
    }

    private void btnSolicitarActionPerformed(java.awt.event.ActionEvent evt) {
        Archivo archivo = new Archivo();
        archivo.crearArchivo();
        String materia = cbMateria.getSelectedItem().toString();
        String links[] = { "https://meet.google.com/abc-defg-hij", "https://meet.google.com/klm-nopq-rst",
                "https://meet.google.com/uvw-xyz1-234", "https://meet.google.com/567-89ab-cde",
                "https://meet.google.com/xyz-uvw5-678", "https://meet.google.com/pqr-stu2-vwx",
                "https://meet.google.com/345-67fg-hij", "https://meet.google.com/def-abc8-901",
                "https://meet.google.com/opq-rst3-456", "https://meet.google.com/xyz-uvw7-890",
                "https://meet.google.com/abc-defg-hij", "https://meet.google.com/klm-nopq-rst",
                "https://meet.google.com/uvw-xyz1-234", "https://meet.google.com/567-89ab-cde",
                "https://meet.google.com/xyz-uvw5-678", "https://meet.google.com/pqr-stu2-vwx",
                "https://meet.google.com/345-67fg-hij", "https://meet.google.com/def-abc8-901",
                "https://meet.google.com/opq-rst3-456", "https://meet.google.com/xyz-uvw7-890"
        };

        Random rd = new Random();
        String link = links[rd.nextInt(links.length)];
        String fecha = tfFechaNuevaSesion.getText();
        fecha = fecha.replace("01", "");

        Sesion ses = new Sesion(materia, link, fecha);
        archivo.escribirEnArchivo(ses);
        JOptionPane.showMessageDialog(null, "SE HIZO LA SOLICITUD.");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaCalendario.class.getName()).log(java.util.logging.Level.SEVERE,
                    null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaCalendario.class.getName()).log(java.util.logging.Level.SEVERE,
                    null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaCalendario.class.getName()).log(java.util.logging.Level.SEVERE,
                    null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaCalendario.class.getName()).log(java.util.logging.Level.SEVERE,
                    null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaCalendario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalendario;
    private javax.swing.JButton btnCambiarCuenta;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCuenta;
    private javax.swing.JButton btnSesiones;
    private javax.swing.JButton btnSolicitar;
    private javax.swing.JButton btnVerListaEstudiantes;
    private java.awt.Canvas canvas1;
    private javax.swing.JComboBox<String> cbHora;
    private javax.swing.JComboBox<String> cbMateria;
    private com.toedter.calendar.JCalendar jCalendar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfFechaNuevaSesion;
    // End of variables declaration//GEN-END:variables
}
