/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISUAL.Pantallas.Estudiante;

import VISUAL.Pantallas.General.PantallaRegistro;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.Observable;
import java.util.Observer;

import javax.swing.JOptionPane;

import CODE.Clases.Cliente;
import CODE.Clases.Conexion;

/**
 *
 * @author tutaa
 */
@SuppressWarnings("deprecation")
public class PantallaChatEstudiante extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form PantallaChatEstudiante
     */
    private String nombre, mensaje;
    private Cliente cliente;

    public PantallaChatEstudiante() {
        initComponents();
        setDefaultCloseOperation(0);
        tfConversacion.setEnabled(false);
        this.setLocationRelativeTo(null);
        this.setTitle("CHAT");
        this.setResizable(false);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/VISUAL/Imagenes/Logos/icon.png")));

        iniciandoChat();
    }

    public void iniciandoChat() {
        Conexion cx = new Conexion();
        String correoBuscar = PantallaRegistro.correoPoner;
        try {
            cx.con = Conexion.getConection();
            cx.ps = cx.con.prepareCall("SELECT nombre FROM usuarios WHERE correo = ?");
            cx.ps.setString(1, correoBuscar);
            cx.rs = cx.ps.executeQuery();

            if (cx.rs.next()) {
                String nombreCompleto = cx.rs.getString("nombre");
                String primerNombre = nombreCompleto.split(" ")[0];
                nombre = primerNombre;
                cliente = new Cliente(6000);
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró el nombre del usuario con correo " + correoBuscar);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al consultar la base de datos:\n" + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al iniciar el chat:\n" + e.getMessage());
        } finally {
            try {
                if (cx.con != null) {
                    cx.con.close();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null,
                        "Error al cerrar la conexión con la base de datos:\n" + e.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfMensaje = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfConversacion = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(247, 251, 252));
        setFocusCycleRoot(false);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfMensaje.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tfMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 365, 312, -1));

        btnEnviar.setBackground(new java.awt.Color(185, 215, 234));
        btnEnviar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(118, 159, 205));
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 362, -1, -1));

        btnSalir.setBackground(new java.awt.Color(185, 215, 234));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(118, 159, 205));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 401, -1, -1));

        tfConversacion.setBackground(new java.awt.Color(255, 255, 255));
        tfConversacion.setColumns(20);
        tfConversacion.setRows(5);
        jScrollPane1.setViewportView(tfConversacion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 68, 393, 276));

        jLabel7.setFont(new java.awt.Font("Crabs", 1, 55)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(118, 159, 205));
        jLabel7.setText("Chat");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {
        mensaje = tfMensaje.getText();

        cliente.enviarMensaje(nombre + " --> " + mensaje + "\n");

        tfMensaje.setText("");
    }

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaChatEstudiante.class.getName()).log(
                    java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaChatEstudiante.class.getName()).log(
                    java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaChatEstudiante.class.getName()).log(
                    java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaChatEstudiante.class.getName()).log(
                    java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaChatEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tfConversacion;
    private javax.swing.JTextField tfMensaje;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        tfConversacion.append((String) arg);
    }
}
